### ISSUE TITLE
Intro to cs50

### ISSUE THREAD

**Issue by chirathr** [amfoss/vidyaratna#15]
This is already completed thank to @abhinand4858.  We should add more details on how to add their solutions links(If it's a good idea).

**Comment by vchrombie** [comment]
Please have a look at this @vaishnav04.

See that the previous work is already present in the [old branch](https://github.com/amfoss/vidyaratna/tree/initial). Reframe the content and send a PR to the [master branch](https://github.com/amfoss/vidyaratna/tree/master).
