### ISSUE TITLE
Add tasks

### ISSUE THREAD

**Issue by vchrombie** [amfoss/vidyaratna#34]
As of now, we have resources in the readme, how about creating a new file like `tasks.md` and add relevant tasks for each section of resources.

Example:
For GitHub, @chirathr has created an assignment in the previous version. https://github.com/amfoss/vidyaratna/blob/initial/beginners/5_github.md#assignment

We can recreate such things and add assignments for every category.

Would like to hear your views on this. :slightly_smiling_face:

**Comment by yashk2000** [comment]
@vchrombie great idea :rocket: 

For the android section, we can have the Android Codelabs. They fundamental codelabs will be great a great assignment for learning. 

For linux, bash scripting particularly, people could maybe attempt the higher levels of bandit. Besides this, there are some basic CTF challenges that need bash scripts(concepts like looping, extracting tar, bzip2 files and so on) to be solved.

**Comment by vchrombie** [comment]
Any more opinions?
@akhilam512 @vaishnav04 @harshithpabbati

**Comment by akhilam512** [comment]
Sounds like a great idea @vchrombie 

I guess we can move forward and start assigning tasks to each topic?

**Comment by vchrombie** [comment]
Awesome then. Please send the tasks whenever you are free with the topic you are familiar with. :slightly_smiling_face:

**Comment by vchrombie** [comment]
I suggest the idea of moving the readme contents to resources.md and create another file tasks.md for the assignments.

**Comment by yashk2000** [comment]
> I suggest the idea of moving the readme contents to resources.md and create another file tasks.md for the assignments.

@vchrombie yeah this should be done since we'll be adding tasks too. Separate files is a good idea. Should I open an issue for this?

**Comment by t5ar** [comment]
This can be added as a big picture
 https://frontendmasters.com/guides/learning-roadmap/

**Comment by t5ar** [comment]
Add a Course on Learn How to learn from coursera.com

**Comment by t5ar** [comment]
Add TODO To Read the Book Clean Code to improve coding standards
