### ISSUE TITLE
Write about the task on install Linux

### ISSUE THREAD

**Issue by chirathr** [amfoss/vidyaratna#8]
- We can go with Ubuntu 18.04 LTS
- Mention about why we use Linux
- Links to resources and tutorials(With a little description of the resource)
- Common Errors and Issues Faced

**Comment by vchrombie** [comment]
@akhilam512 

> * Links to resources and tutorials(With a little description of the resource)

This is done. :tada: 

> * Common Errors and Issues Faced

Can you check the [another branch](https://github.com/amfoss/vidyaratna/tree/initial) and maybe you can fill this section? :thinking:

**Comment by akhilam512** [comment]
> I think as aforementioned, we can add it in the main readme itself under Linux ->  "Installation and Dual-booting" but only the smaller topics like "Why Linux" and "Installation"  from [here](https://github.com/amfoss/vidyaratna/blob/initial/beginners/0_install_linux.md)  and the leave bigger, more elaborate (Common issues, laptop suggestions) ones in a separate md file. What do you think?  

`

_Originally posted by @akhilam512 in https://github.com/amfoss/vidyaratna/issues/9#issuecomment-499429738_

I think with #9 we will cover the rest of the things, we can update that info if need be.

**Comment by vchrombie** [comment]
Please close this issue when it is done.
