### ISSUE TITLE
Recommendation of laptops

### ISSUE THREAD

**Issue by chirathr** [amfoss/vidyaratna#9]
Since many of us face issues with drivers on Linux, we could create a list of laptops that are compatible.
This can be added as a section in 0_install_linux.md

**Comment by chirath02** [comment]
Then we can mention that if 18.04 does not work, they can try 17.10?

**Comment by Sparker0i** [comment]
17.10 will become dated within a few months. 16.04 will still have support.
Let's tell 16.04 then

**Comment by vchrombie** [comment]
@akhilam512 
Can you please look into this?

**Comment by vchrombie** [comment]
What do you think?
should we add this in the readme or create a seperate md file?

**Comment by akhilam512** [comment]
I think as aforementioned, we can add it in the main readme itself under Linux ->  "Installation and Dual-booting" but only the smaller topics like "Why Linux" and "Installation"  from [here](https://github.com/amfoss/vidyaratna/blob/initial/beginners/0_install_linux.md)  and the leave bigger, more elaborate (Common issues, laptop suggestions) ones in a separate md file. What do you think?  
`

- we can put it under headings like "Why Linux?" , "Common problems" and "Laptop Suggestions" inthe main

**Comment by vchrombie** [comment]
> I think as aforementioned, we can add it in the main readme itself under Linux -> "Installation and Dual-booting" but only the smaller topics like "Why Linux" and "Installation" from [here](https://github.com/amfoss/vidyaratna/blob/initial/beginners/0_install_linux.md) and the leave bigger, more elaborate (Common issues, laptop suggestions) ones in a separate md file. What do you think?

Is a new file required?

laptop suggestions can be mentioned in the readme while the common issues can be added as a ref to some blog post, it would be good if someone can blog about it else we need to wait for it.

**Comment by akhilam512** [comment]
Okay, I'm up for it if it fits and is not tooo long. I'll experiment and send a PR.
